version: "3.8"

services:
    zookeeper:
        image: "bitnami/zookeeper:3.6.1"
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: "bitnami/kafka:2.6.0"
        ports:
            - "9092:9092"
            - "9093:9093"
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_BROKER_ID=1
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=EXTERNAL://0.0.0.0:9093,INTERNAL://0.0.0.0:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://kafka:9093,INTERNAL://localhost:9092
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
        depends_on:
            - zookeeper
    postgresql:
        image: "bitnami/postgresql:12.4.0"
        ports:
            - "5432:5432"
        volumes:
            - "./sql:/docker-entrypoint-initdb.d"
            - "./postgresql_data:/bitnami/postgresql"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - POSTGRESQL_DATABASE=helios
    spark-master:
        image: bitnami/spark:3.0.1
        ports:
            - "8080:8080"
    spark-worker-1:
        image: bitnami/spark:3.0.1
        volumes:
            - "./data:/app/data"
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
    spark-worker-2:
        image: bitnami/spark:3.0.1
        volumes:
            - "./data:/app/data"
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
    spark-client:
        image: bitnami/spark:3.0.1
        depends_on:
            - spark-master
        ports:
            - "4040:4040"
        volumes:
            - "./data:/app/data"
            - "./target:/app"
        working_dir: "/app"
        environment:
            - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
            - POSTGRESQL_URL=jdbc:postgresql://postgresql:5432/helios
        command: "spark-submit --master spark://spark-master:7077 helios.jar"
